/* The garage: every vehicle the Race and Destruction games offer, in one list (docs/garage-gdd.md has
 * the design). No dependencies: runs in the browser (classic script, global CrashGarage, loaded before
 * js/vehicles.js) and in Node.
 *
 * type 'car': a road car on the crash lattice. Its model is models/<key>.glb.js and .phys.js (the
 * Lexus and Mustang from photographed models, the rest generated by tools/build-vehicle.py), and
 * `lattice` is what js/vehicles.js adds to the spec it builds from the .phys.js: mass, names, the Race
 * tuning (`tune`, read by js/race/vehicle.js; the Lexus and Mustang keep theirs there), the engine's
 * place, the structure's stiffness and (a pickup) the lattice over the open bed. Other types ('bike',
 * 'hover', 'tracked') are rigs: rigid bodies, not on the lattice (js/race/rigs.js); their model is
 * models/<key>.glb.js and .phys.js from tools/build-rig.py, and `rig` holds their mass, tuning and armour.
 *
 * Per entry: key, name, kind (the select list's tag), line (the class line under the name), type,
 * size [L, W, H] (m), paint ({ name, hex }: the signature paint, the one it starts in, added to the
 * select screen's palette; null: it starts in crimson red), targets (the design's numbers: top km/h,
 * t100 s, lateralG g), note (the design's one-liner), race ('ranked' | 'unranked' | false), destruction (bool), rival (AI rivals may drive it).
 * Added from SOUND below: sound (its recorded engine and crash sounds).
 */
(function (root) {
'use strict';

const LIST = [
  { key: 'lexus', name: 'Lexus RX 350', kind: 'SUV', line: 'Midsize SUV · all-wheel drive', type: 'car', size: [4.86, 1.92, 1.75], paint: null,
    race: 'ranked', destruction: true, rival: true,
    lattice: { massKg: 1950, short: 'Lexus RX 350', note: 'midsize SUV', addEngine: true } },   // the model has no engine
  { key: 'mustang', name: 'Ford Mustang GT500', kind: 'Coupe', line: 'Muscle coupe · rear-wheel drive', type: 'car', size: [4.82, 1.96, 1.46], paint: null,
    race: 'ranked', destruction: true, rival: true,
    lattice: { massKg: 1890, short: 'Ford Mustang GT500', note: 'coupe' } },
  { key: 'halcyon', name: 'Halcyon GT', kind: 'Grand tourer', line: 'Grand touring coupe · rear-wheel drive', type: 'car', size: [4.72, 1.92, 1.31],
    paint: { name: 'dusk orange', hex: 0xf28c2c }, targets: { top: 236, t100: 5.2 }, note: '0-100 km/h in 5.2 s',
    race: 'ranked', destruction: true, rival: true,
    lattice: { massKg: 1640, short: 'Halcyon GT', note: 'grand touring coupe', addEngine: true,
      tune: { power: 156e3, cdA: 0.8, drive: [0, 1], grip: 1.12, hcg: 0.48, steer: 0.55, gears: [3.2, 2.1, 1.55, 1.2, 1.0, 0.82, 0.68], final: 3.4, redline: 7400 } } },
  { key: 'wren', name: 'Wren RS', kind: 'Hot hatch', line: 'Hot hatch · front-wheel drive', type: 'car', size: [3.95, 1.78, 1.46],
    paint: { name: 'pale violet', hex: 0xb49cec }, targets: { top: 198, lateralG: 0.94 }, note: '0.94 g cornering grip',
    race: 'ranked', destruction: true, rival: true,
    lattice: { massKg: 1240, short: 'Wren RS', note: 'hot hatch', addEngine: true, stiffness: 0.78,
      tune: { power: 79e3, cdA: 0.66, drive: [1, 0], grip: 1.14, hcg: 0.52, steer: 0.6, gears: [3.4, 2.1, 1.5, 1.15, 0.92, 0.78], final: 3.9, redline: 7000 } } },
  { key: 'bastion', name: 'Bastion', kind: 'Full-size SUV', line: 'Full-size SUV · all-wheel drive', type: 'car', size: [5.15, 2.02, 1.88],
    paint: { name: 'deep violet', hex: 0x6444ac }, targets: { top: 190 }, note: 'shoves traffic aside',
    race: 'ranked', destruction: true, rival: true,
    lattice: { massKg: 2480, short: 'Bastion', note: 'full-size SUV', addEngine: true,
      tune: { power: 128e3, cdA: 1.12, drive: [0.4, 0.6], grip: 1, hcg: 0.72, steer: 0.5, gears: [4.2, 2.6, 1.7, 1.25, 1.0, 0.8, 0.65], final: 3.2, redline: 6000 } } },
  { key: 'quasar', name: 'Quasar LM', kind: 'Prototype', line: 'Endurance prototype · mid-engine', type: 'car', size: [4.65, 2.0, 1.05],
    paint: { name: 'lab white', hex: 0xe6e6ea }, targets: { top: 290, t100: 3.1 }, note: '0-100 km/h in 3.1 s',
    race: 'ranked', destruction: true, rival: true,
    lattice: { massKg: 1180, short: 'Quasar LM', note: 'endurance prototype', addEngine: true, engine: 'mid',
      tune: { power: 216e3, cdA: 0.64, drive: [0, 1], grip: 1.32, hcg: 0.36, steer: 0.5, cgf: 0.42, launch: 1.1, gears: [2.9, 2.15, 1.7, 1.38, 1.15, 0.98], final: 3.1, redline: 9000 } } },
  { key: 'ridgeback', name: 'Ridgeback', kind: 'Pickup', line: 'Crew-cab pickup · four-wheel drive', type: 'car', size: [5.75, 2.03, 1.9],
    paint: { name: 'amber', hex: 0xf09c4c }, targets: { top: 180 }, note: '3.70 m wheelbase',
    race: 'ranked', destruction: true, rival: true,
    lattice: { massKg: 2310, short: 'Ridgeback', note: 'crew-cab pickup', addEngine: true, bedTop: [0.09, 2.51, 1.38],
      tune: { power: 114e3, cdA: 1.2, drive: [0.45, 0.55], grip: 0.98, hcg: 0.75, steer: 0.48, gears: [4.0, 2.4, 1.6, 1.2, 1.0, 0.75], final: 3.4, redline: 5600 } } },
  { key: 'ember', name: 'Ember 440', kind: 'Cruiser', line: 'Boulevard cruiser · 1960s land yacht', type: 'car', size: [5.6, 2.01, 1.42],
    paint: { name: 'ember red', hex: 0xc47c84 }, targets: { top: 205 }, note: 'soft springs, big slides',
    race: 'ranked', destruction: true, rival: true,
    lattice: { massKg: 2050, short: 'Ember 440', note: 'land yacht', addEngine: true,
      tune: { power: 128e3, cdA: 0.92, drive: [0, 1], grip: 0.94, hcg: 0.62, steer: 0.5, rearGrip: 0.9, lean: 1.8, gears: [2.5, 1.5, 1.0], final: 3.2, redline: 4800 } } },
  { key: 'cadence', name: 'Cadence SE', kind: 'Sport sedan', line: 'Compact sport sedan · front-wheel drive', type: 'car', size: [4.55, 1.8, 1.42],
    paint: { name: 'slate gray', hex: 0x8c9494 }, targets: { top: 218, t100: 6.8 }, note: '0-100 km/h in 6.8 s',
    race: 'ranked', destruction: true, rival: true,
    lattice: { massKg: 1420, short: 'Cadence SE', note: 'compact sport sedan', addEngine: true,
      tune: { power: 126e3, cdA: 0.83, drive: [1, 0], grip: 1.06, hcg: 0.52, steer: 0.55, gears: [3.5, 2.1, 1.45, 1.1, 0.9, 0.75], final: 3.7, redline: 6800 } } },
  { key: 'kestrel', name: 'Kestrel 900', kind: 'Motorcycle', line: 'Sport motorcycle · inline-four', type: 'bike', size: [2.1, 0.76, 1.15],
    paint: { name: 'violet', hex: 0x8c64f4 }, targets: { top: 262, t100: 3.0 }, note: '0-100 km/h in 3.0 s',
    race: 'ranked', destruction: true, rival: false,
    rig: { massKg: 205, riderKg: 80,
      tune: { power: 84e3, cdA: 0.35, drive: [0, 1], grip: 1.18, hcg: 0.62, steer: 0.5, launch: 1.0, cgf: 0.5, gears: [2.6, 1.9, 1.5, 1.25, 1.08, 0.96], final: 2.9, redline: 14000 } } },
  { key: 'osprey', name: 'Osprey', kind: 'Drone', line: 'Hexacopter cargo drone · hovers 0.6 m up', type: 'hover', size: [2.33, 2.6, 0.7],
    paint: { name: 'peach', hex: 0xecccac }, targets: { top: 140 }, note: 'hops the traffic, no grip',
    race: 'ranked', destruction: true, rival: false,
    // thrust: forward push (x weight), slide: how fast sideways speed dies away (1/s), steer: yaw rate
    rig: { massKg: 180, tune: { power: 45e3, cdA: 1.27, thrust: 0.9, slide: 0.8, steer: 1.6, gears: [1], final: 1, redline: 9000 } } },
  { key: 'rampart', name: 'Rampart', kind: 'Tank', line: 'Light tank · tracked · 11.8 t', type: 'tracked', size: [7.2, 3.1, 2.4],
    paint: { name: 'rust', hex: 0x6c3c14 }, targets: { top: 72 }, note: 'a solver box, like the bus',
    race: 'unranked', destruction: true, rival: false,
    // vmax: the governor (m/s; vmaxBoost with boost), grip: sideways (x weight), steer: pivot turn (rad/s)
    rig: { massKg: 11800, armour: { car: 0, wall: 0.25, post: 0.25 },
      tune: { power: 350e3, cdA: 2.6, vmax: 20, vmaxBoost: 22.2, grip: 0.9, steer: 0.9, gears: [3.5, 2.2, 1.4, 1.0], final: 6, redline: 2600 } } },
];

// Each vehicle's recorded sounds (js/fx.js; the clips are cut from the recordings in media/audio by
// tools/build-sfx.py). idle and drive: engine loops pitched with the revs, idle at low revs crossfading
// to drive above about twice idle; tracks: a loop that follows the speed; pitch: scales the revs, for a
// recording of another engine; start: plays in the garage when the vehicle is picked; crash: at its
// crash's first impact (the bike and the drone, whose crashes aren't on the lattice).
const SOUND = {
  lexus: { idle: 'idle-petrol', drive: 'drive-porsche', pitch: 0.9 },
  mustang: { idle: 'idle-impala', drive: 'drive-muscle', start: 'rev-v8' },
  halcyon: { idle: 'idle-lotus', drive: 'drive-porsche', start: 'rev-lotus' },
  wren: { idle: 'idle-petrol', drive: 'drive-fox', pitch: 1.1 },
  bastion: { idle: 'idle-impala', drive: 'drive-muscle', pitch: 0.85 },
  quasar: { idle: 'idle-lotus', drive: 'drive-bike', start: 'start-lotus' },
  ridgeback: { drive: 'idle-diesel', pitch: 0.45 },
  ember: { idle: 'idle-impala', drive: 'drive-muscle', pitch: 0.9, start: 'rev-impala' },
  cadence: { idle: 'idle-petrol', drive: 'drive-fox' },
  kestrel: { idle: 'idle-bike', drive: 'drive-bike', start: 'start-bike', crash: 'crash-bike' },
  osprey: { drive: 'drone', crash: 'crash-drone' },
  rampart: { drive: 'tank-engine', tracks: 'tank-tracks', pitch: 0.8, start: 'rev-tank' },
};

const byKey = {};
for (const v of LIST) { byKey[v.key] = v; v.sound = SOUND[v.key] || null; }

const api = {
  LIST,
  get: (key) => byKey[key] || null,
  keys: LIST.map(v => v.key),
  // road cars on the crash lattice (their models are the exporter's .glb.js and .phys.js)
  latticeKeys: LIST.filter(v => v.type === 'car').map(v => v.key),
  raceKeys: LIST.filter(v => v.race).map(v => v.key),
  destructionKeys: LIST.filter(v => v.destruction).map(v => v.key),
  rivalKeys: LIST.filter(v => v.rival).map(v => v.key),
};
root.CrashGarage = api;
if (typeof module === 'object' && module.exports) module.exports = api;
})(typeof window !== 'undefined' ? window : globalThis);
