/* The soundtrack for the pages (js/music.js):
 *   node tools/build-music.js                       wraps every media/music/<song>.mp3 as media/music/<song>.js
 *                                                   (base64 in a classic script, so it loads from file:// too)
 *   node tools/build-music.js --analyze <song> [--range a0,a1,b0,b1] [--chrome <chrome.exe>]
 *                                                   measures a song in headless Chrome and suggests its entry for
 *                                                   SONGS in js/music.js: the loudness trim to -16 LUFS and a loop
 *                                                   splice; writes a picture of the splice to tools/out/music-<song>.jpg
 *
 * The loop: the song leaves at A (late in the song) and goes on from B (early), where the 6 s before each
 * point have the same rhythm (onsets in four bands, at 10 ms) and much the same sound (band energies).
 * A is searched over a0..a1 (default the last 25 s but 3) and B over b0..b1 (default 3 s to A - 45 s).
 * The pair is refined below 10 ms, then the splice is moved to 25 ms before a drum hit both places
 * share, with B shifted so the two hits line up to the millisecond. The picture shows the song straight
 * through at A, the spliced result and the song at B, lined up at the splice: drum hits should make
 * unbroken vertical stripes, and the onset traces (red at A, green at B) should peak together before it.
 * The tempo of these songs isn't a clean grid, so look at the picture before taking the numbers. */
'use strict';
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawn } = require('child_process');

const root = path.join(__dirname, '..');
const dir = path.join(root, 'media', 'music');
const arg = (k, d) => { const i = process.argv.indexOf(k); return i > 0 ? process.argv[i + 1] : d; };

if (!process.argv.includes('--analyze')) {
  for (const f of fs.readdirSync(dir).filter((f) => f.endsWith('.mp3'))) {
    const song = f.slice(0, -4), b64 = fs.readFileSync(path.join(dir, f)).toString('base64');
    const js = `/* Generated by tools/build-music.js from ${f}. Do not edit; re-run the tool. */\n` +
      `(window.MUSIC_DATA = window.MUSIC_DATA || {})[${JSON.stringify(song)}] = '${b64}';\n`;
    fs.writeFileSync(path.join(dir, song + '.js'), js);
    console.log(`wrote media/music/${song}.js: ${(js.length / 1048576).toFixed(1)} MB`);
  }
  process.exit(0);
}

// ---------------------------------------------------------------- analysis (runs in the page)
const PAGE = String.raw`
const fftOf = (W) => { const re = new Float32Array(W), im = new Float32Array(W), rev = new Uint32Array(W);
  for (let i = 0, j = 0; i < W; i++) { rev[i] = j; let bit = W >> 1; while (j & bit) { j ^= bit; bit >>= 1; } j |= bit; }
  const run = () => { for (let i = 0; i < W; i++) { const j = rev[i]; if (j > i) { let t = re[i]; re[i] = re[j]; re[j] = t; t = im[i]; im[i] = im[j]; im[j] = t; } }
    for (let size = 2; size <= W; size <<= 1) { const h = size >> 1, th = -2 * Math.PI / size; for (let s = 0; s < W; s += size) for (let k = 0; k < h; k++) { const wr = Math.cos(th * k), wi = Math.sin(th * k), a = s + k, b = a + h, tr = re[b] * wr - im[b] * wi, ti = re[b] * wi + im[b] * wr; re[b] = re[a] - tr; im[b] = im[a] - ti; re[a] += tr; im[a] += ti; } } };
  return { re, im, run }; };
const hann = (W) => Float32Array.from({ length: W }, (_, i) => 0.5 - 0.5 * Math.cos(2 * Math.PI * i / W));
// integrated loudness, ITU-R BS.1770 (K-weighting, 400 ms blocks, gated)
function lufs(buf) {
  const sr = buf.sampleRate, N = buf.length;
  const bq = (x, b0, b1, b2, a1, a2) => { const y = new Float32Array(x.length); let x1 = 0, x2 = 0, y1 = 0, y2 = 0; for (let i = 0; i < x.length; i++) { const v = b0 * x[i] + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2; x2 = x1; x1 = x[i]; y2 = y1; y1 = v; y[i] = v; } return y; };
  const kw = (x) => { let G = 3.99984385397, Q = 0.7071752369554193, fc = 1681.9744509555319, A = Math.pow(10, G / 40), w = 2 * Math.PI * fc / sr, al = Math.sin(w) / (2 * Q), c = Math.cos(w), sA = 2 * Math.sqrt(A) * al, a0 = (A + 1) - (A - 1) * c + sA;
    const s = bq(x, A * ((A + 1) + (A - 1) * c + sA) / a0, -2 * A * ((A - 1) + (A + 1) * c) / a0, A * ((A + 1) + (A - 1) * c - sA) / a0, 2 * ((A - 1) - (A + 1) * c) / a0, ((A + 1) - (A - 1) * c - sA) / a0);
    Q = 0.5003270373253953; fc = 38.13547087613982; w = 2 * Math.PI * fc / sr; al = Math.sin(w) / (2 * Q); c = Math.cos(w); const b = 1 + al;
    return bq(s, (1 + c) / 2 / b, -(1 + c) / b, (1 + c) / 2 / b, -2 * c / b, (1 - al) / b); };
  const L = kw(buf.getChannelData(0)), R = kw(buf.getChannelData(buf.numberOfChannels > 1 ? 1 : 0));
  const blk = Math.round(0.4 * sr), hop = Math.round(0.1 * sr), z = [];
  for (let s = 0; s + blk <= N; s += hop) { let a = 0; for (let i = s; i < s + blk; i++) a += L[i] * L[i] + R[i] * R[i]; z.push(a / blk); }
  const lk = (m) => -0.691 + 10 * Math.log10(m), mean = (a) => a.reduce((p, q) => p + q, 0) / a.length;
  let g = z.filter((m) => lk(m) > -70); const rel = lk(mean(g)) - 10; g = g.filter((m) => lk(m) > rel);
  return lk(mean(g));
}
// onsets (positive log-magnitude change) and energy in four bands, every 10 ms
function bands(buf) {
  const sr = buf.sampleRate, L = buf.getChannelData(0), R = buf.getChannelData(1), W = 2048, H = Math.round(sr / 100), F = Math.floor((buf.length - W) / H);
  const B = [[1, 6], [6, 24], [24, 90], [90, 400]], f = fftOf(W), win = hann(W), on = B.map(() => new Float32Array(F)), en = B.map(() => new Float32Array(F));
  let prev = new Float32Array(400);
  for (let t = 0; t < F; t++) { const o = t * H; for (let i = 0; i < W; i++) { f.re[i] = 0.5 * (L[o + i] + R[o + i]) * win[i]; f.im[i] = 0; } f.run();
    const cur = new Float32Array(400);
    for (let q = 0; q < 4; q++) for (let k = B[q][0]; k < B[q][1]; k++) { const m = Math.log(1 + 100 * Math.hypot(f.re[k], f.im[k])); cur[k] = m; en[q][t] += m; if (m > prev[k]) on[q][t] += m - prev[k]; }
    prev = cur; }
  return { on, en, off: W / 2 / sr };
}
const prefix = (f) => { const s = new Float64Array(f.length + 1), ss = new Float64Array(f.length + 1); for (let i = 0; i < f.length; i++) { s[i + 1] = s[i] + f[i]; ss[i + 1] = ss[i] + f[i] * f[i]; } return { f, s, ss }; };
function corr(P, ia, ib, n) { const { f, s, ss } = P; let ab = 0; for (let i = 0; i < n; i++) ab += f[ia - n + i] * f[ib - n + i];
  const a = s[ia] - s[ia - n], b = s[ib] - s[ib - n], aa = ss[ia] - ss[ia - n], bb = ss[ib] - ss[ib - n];
  return (ab - a * b / n) / Math.sqrt(Math.max(1e-9, (aa - a * a / n) * (bb - b * b / n))); }
const smooth = (x, r) => { const n = x.length, cs = new Float64Array(n + 1); for (let i = 0; i < n; i++) cs[i + 1] = cs[i] + x[i]; return Float32Array.from(x, (_, i) => { const lo = Math.max(0, i - r), hi = Math.min(n, i + r + 1); return (cs[hi] - cs[lo]) / (hi - lo); }); };
const novelty = (x, r) => { const m = smooth(x, r); return Float32Array.from(x, (v, i) => Math.max(0, v - m[i])); };
const gauss = (x, sg) => { const r = Math.ceil(3 * sg), k = Array.from({ length: 2 * r + 1 }, (_, i) => Math.exp(-0.5 * ((i - r) / sg) ** 2)), ks = k.reduce((p, q) => p + q, 0);
  return Float32Array.from(x, (_, i) => { let s = 0; for (let j = -r; j <= r; j++) s += (x[i + j] || 0) * k[j + r]; return s / ks; }); };
// onsets every 1 ms (512-point spectra), for placing the splice
function fine(buf, t0, t1) {
  const sr = buf.sampleRate, L = buf.getChannelData(0), R = buf.getChannelData(1), W = 512, H = Math.round(sr / 1000);
  const i0 = Math.max(0, Math.round(t0 * sr) - W / 2), F = Math.floor((Math.min(buf.length, Math.round(t1 * sr)) - i0 - W) / H), f = fftOf(W), win = hann(W), on = new Float32Array(F);
  let prev = new Float32Array(W / 2);
  for (let t = 0; t < F; t++) { const o = i0 + t * H; for (let i = 0; i < W; i++) { f.re[i] = 0.5 * (L[o + i] + R[o + i]) * win[i]; f.im[i] = 0; } f.run();
    const cur = new Float32Array(W / 2); for (let k = 2; k < W / 2; k++) { const m = Math.log(1 + 100 * Math.hypot(f.re[k], f.im[k])); cur[k] = m; if (m > prev[k]) on[t] += m - prev[k]; } prev = cur; }
  const n = novelty(on, 40), K = [1, 4, 9, 14, 16, 14, 9, 4, 1];
  return { env: Float32Array.from(n, (_, i) => K.reduce((a, w, j) => a + w * (n[i + j - 4] || 0), 0) / 72), t0: (i0 + W / 2) / sr };
}
window.analyze = async (b64, range) => {
  const bin = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
  const buf = await new OfflineAudioContext(2, 1, 44100).decodeAudioData(bin.buffer), dur = buf.duration;
  const loud = lufs(buf), { on, en } = bands(buf), fr = 100, WIN = 600;
  const rh = on.map((x) => prefix(gauss(novelty(x, 15), 2.5))), tb = en.map((x) => prefix(smooth(x, 25)));
  const score = (ia, ib) => { let r = 0, t = 0; for (const P of rh) r += corr(P, ia, ib, WIN); for (const P of tb) t += corr(P, ia, ib, WIN); return [r / 4, t / 4]; };
  const [a0, a1, b0, b1] = range || [dur - 25, dur - 3, 3, dur - 70];
  const cands = [];
  for (let ta = a0; ta <= a1; ta += 0.25) { const ia = Math.round(ta * fr); let best = null;
    for (let ib = Math.max(WIN, Math.round(b0 * fr)); ib <= Math.round(Math.min(b1, ta - 45) * fr); ib++) { const [r, t] = score(ia, ib), c = 0.7 * r + 0.3 * t; if (!best || c > best[0]) best = [c, ib, r, t]; }
    if (best) cands.push({ A: ta, B: best[1] / fr, score: +best[0].toFixed(3), rhythm: +best[2].toFixed(3), sound: +best[3].toFixed(3) }); }
  cands.sort((x, y) => y.score - x.score);
  if (!cands.length) throw new Error('no loop in that range');
  const top = cands[0], ia = Math.round(top.A * fr), sc = (ib) => rh.reduce((s, P) => s + corr(P, ia, ib, WIN), 0) / 4;
  // beat check: the rhythm match at the pair and a beat-ish either side
  const sharp = [-30, -15, 0, 15, 30].map((d) => +sc(Math.round(top.B * fr) + d).toFixed(2));
  // below 10 ms: a parabola through the peak (+-60 ms)
  let pk = [-9, 0]; for (let ib = Math.round(top.B * fr) - 6; ib <= Math.round(top.B * fr) + 6; ib++) { const v = sc(ib); if (v > pk[0]) pk = [v, ib]; }
  const cm = sc(pk[1] - 1), cp = sc(pk[1] + 1), B1 = (pk[1] + 0.5 * (cm - cp) / (cm - 2 * pk[0] + cp)) / fr;
  // the splice: 25 ms before the strongest hit both share within -0.6..+0.3 s, the hits lined up
  const EA = fine(buf, top.A - 1, top.A + 0.5), EB = fine(buf, B1 - 1, B1 + 0.5);
  const mf = (e) => Float32Array.from(e, (_, i) => { let m = 0; for (let j = -12; j <= 12; j++) m = Math.max(m, e[i + j] || 0); return m; });
  const ma = mf(EA.env), mb = mf(EB.env), xa = Math.round((top.A - EA.t0) * 1000), xb = Math.round((B1 - EB.t0) * 1000);
  let hit = [-1, 0]; for (let d = -600; d <= 300; d++) { const v = Math.min(ma[xa + d], mb[xb + d]); if (v > hit[0]) hit = [v, d]; }
  const rise = (E, x0) => { let o = hit[1], r = -1; for (let d = hit[1] - 15; d <= hit[1] + 15; d++) { const v = (E[x0 + d] || 0) - (E[x0 + d - 3] || 0); if (v > r) { r = v; o = d; } } return o; };
  const onA = rise(EA.env, xa), onB = rise(EB.env, xb), s = (onA - 25) / 1000;
  return { duration: +dur.toFixed(3), lufs: +loud.toFixed(2), db: +(-16 - loud).toFixed(1), loop: [+(top.A + s).toFixed(3), +(B1 + (onB - onA) / 1000 + s).toFixed(3)], candidates: cands.slice(0, 6), rhythmAround: sharp };
};
// the picture: spectrograms of the song at A, the splice, the song at B, and the onset traces
window.picture = async (b64, A, B, name) => {
  const bin = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
  const buf = await new OfflineAudioContext(2, 1, 44100).decodeAudioData(bin.buffer), sr = buf.sampleRate, X = 0.04, pre = 2, post = 2;
  const render = async (a, b) => { const c = new OfflineAudioContext(2, Math.round((pre + post) * sr), sr), t0 = pre - X / 2, t1 = pre + X / 2;
    const v1 = c.createBufferSource(), g1 = c.createGain(), v2 = c.createBufferSource(), g2 = c.createGain(); v1.buffer = v2.buffer = buf;
    v1.connect(g1).connect(c.destination); v2.connect(g2).connect(c.destination);
    g1.gain.setValueAtTime(1, t0); g1.gain.linearRampToValueAtTime(0, t1); g2.gain.setValueAtTime(0, 0); g2.gain.setValueAtTime(0, t0); g2.gain.linearRampToValueAtTime(1, t1);
    v1.start(0, a - pre); v1.stop(t1); v2.start(t0, b - X / 2); return c.startRendering(); };
  const sa = await render(A, A), cut = await render(A, B), sb = await render(B, B);
  const Wpx = 1200, rowH = 150, cv = document.createElement('canvas'); cv.width = Wpx; cv.height = 3 * rowH + 150;
  const g = cv.getContext('2d'); g.fillStyle = '#000'; g.fillRect(0, 0, cv.width, cv.height); g.font = '13px monospace';
  const N = 1024, f = fftOf(N), win = hann(N);
  [['at A ' + A, sa], ['spliced', cut], ['at B ' + B, sb]].forEach(([label, b], r) => {
    const L = b.getChannelData(0), R = b.getChannelData(1), img = g.createImageData(Wpx, rowH), spx = (pre + post) * sr / Wpx;
    for (let x = 0; x < Wpx; x++) { const c = Math.round(x * spx) - N / 2; for (let i = 0; i < N; i++) { f.re[i] = ((L[c + i] || 0) + (R[c + i] || 0)) * win[i]; f.im[i] = 0; } f.run();
      for (let y = 0; y < rowH; y++) { const k = Math.max(1, Math.round(40 * Math.pow(300, (rowH - 1 - y) / (rowH - 1)) * N / sr)), v = Math.max(0, Math.min(255, (20 * Math.log10(Math.hypot(f.re[k], f.im[k]) + 1e-6) + 10) * 5.5)), o = (y * Wpx + x) * 4;
        img.data[o] = v; img.data[o + 1] = v * 0.8; img.data[o + 2] = 255 - v * 0.6; img.data[o + 3] = 255; } }
    g.putImageData(img, 0, 20 + r * rowH); g.fillStyle = '#ff0'; g.fillText(label, 6, 34 + r * rowH);
  });
  const top = 30 + 3 * rowH, hgt = 110, traces = [[sa, '#ff4040', 2], [sb, '#40ff40', 2]].map(([b, col, w]) => [fine(b, 0.05, pre + post - 0.05), col, w]);
  const all = traces.flatMap(([E]) => Array.from(E.env.subarray(60))).sort((p, q) => p - q), mx = all[Math.floor(all.length * 0.995)];
  for (const [E, col, w] of traces) { g.strokeStyle = col; g.lineWidth = w; g.beginPath(); E.env.forEach((v, i) => { const x = (E.t0 + i / 1000) / (pre + post) * Wpx, y = top + hgt - Math.min(1, v / mx) * hgt; if (i) g.lineTo(x, y); else g.moveTo(x, y); }); g.stroke(); }
  g.strokeStyle = 'rgba(255,0,0,0.9)'; g.lineWidth = 1; g.beginPath(); g.moveTo(Wpx / 2, 18); g.lineTo(Wpx / 2, cv.height); g.stroke();
  g.fillStyle = '#fff'; g.fillText(name + ': the song at A, spliced, at B (4 s; red line: the splice); onsets: red at A, green at B', 6, 14);
  document.body.style.margin = '0'; document.body.appendChild(cv);
};`;

(async () => {
  const song = arg('--analyze'), mp3 = path.join(dir, song + '.mp3');
  if (!fs.existsSync(mp3)) throw new Error('no ' + path.relative(root, mp3));
  const range = arg('--range') ? arg('--range').split(',').map(Number) : null;
  const chrome = arg('--chrome', 'C:/Program Files/Google/Chrome/Application/chrome.exe');
  const port = 9300 + Math.floor(Math.random() * 400), profile = fs.mkdtempSync(path.join(os.tmpdir(), 'ccs-music-'));
  const proc = spawn(chrome, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${profile}`, '--no-first-run', '--mute-audio', '--window-size=1200,640', 'about:blank'], { stdio: 'ignore' });
  let target;
  for (let i = 0; i < 60 && !target; i++) { await new Promise((r) => setTimeout(r, 250)); try { target = (await (await fetch(`http://127.0.0.1:${port}/json/list`)).json()).find((t) => t.type === 'page'); } catch { /* not up yet */ } }
  if (!target) throw new Error('Chrome did not start (' + chrome + ')');
  const ws = new WebSocket(target.webSocketDebuggerUrl);
  await new Promise((r) => ws.addEventListener('open', r));
  let id = 0; const pending = new Map();
  ws.addEventListener('message', (e) => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } });
  const send = (method, params = {}) => new Promise((resolve, reject) => { const i = ++id; pending.set(i, (m) => m.error ? reject(new Error(m.error.message)) : resolve(m.result)); ws.send(JSON.stringify({ id: i, method, params })); });
  const ev = async (expr) => { const r = await send('Runtime.evaluate', { expression: expr, returnByValue: true, awaitPromise: true }); if (r.exceptionDetails) throw new Error(r.exceptionDetails.exception?.description || r.exceptionDetails.text); return r.result.value; };
  try {
    await send('Emulation.setDeviceMetricsOverride', { width: 1200, height: 600, deviceScaleFactor: 1, mobile: false });
    // a secure context (file://) for the audio APIs
    await send('Page.navigate', { url: 'file:///' + path.join(root, 'tools').replace(/\\/g, '/') + '/' });
    await new Promise((r) => setTimeout(r, 500));
    await ev(PAGE + ';\nwindow.__b64 = ' + JSON.stringify(fs.readFileSync(mp3).toString('base64')) + '; 1');
    const r = await ev(`analyze(window.__b64, ${JSON.stringify(range)})`);
    console.log(`${song}: ${r.duration} s, ${r.lufs} LUFS`);
    console.log('loop candidates (A -> B, score = 0.7 rhythm + 0.3 sound):');
    for (const c of r.candidates) console.log(`  ${c.A} -> ${c.B.toFixed(2)}  score ${c.score} (rhythm ${c.rhythm}, sound ${c.sound})`);
    console.log(`rhythm match at -300, -150, 0, +150, +300 ms from the best: ${r.rhythmAround.join(' ')} (a clear peak at 0 means the beats line up)`);
    console.log(`for SONGS in js/music.js:  db: ${r.db}, loop: [${r.loop.join(', ')}]`);
    await ev(`picture(window.__b64, ${r.loop[0]}, ${r.loop[1]}, ${JSON.stringify(song)})`);
    const out = path.join(root, 'tools', 'out', `music-${song}.jpg`);
    fs.mkdirSync(path.dirname(out), { recursive: true });
    fs.writeFileSync(out, Buffer.from((await send('Page.captureScreenshot', { format: 'jpeg', quality: 88 })).data, 'base64'));
    console.log('picture: ' + path.relative(root, out));
  } finally { try { ws.close(); } catch { /* closed */ } proc.kill(); }
})().catch((e) => { console.error(e.message); process.exit(1); });
