"""Download the Race game's photo textures and sky from Poly Haven (CC0) and pack them for the page.

    blender -b -Y --factory-startup --python tools/fetch-race-assets.py

Blender is used only for its image library (scale, JPEG quality); no scene is involved. Writes
media/race/assets.js: window.RACE_ASSETS = { name: base64, ... }, a classic script so the game also
works from a file opened from disk. Every asset is CC0 (polyhaven.com/license): no attribution is
required, but the README credits Poly Haven and lists them.
"""
import base64, json, os, sys, tempfile, urllib.request

import bpy

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'media', 'race', 'assets.js')
API = 'https://api.polyhaven.com/files/'

# asset id -> maps to take: (Poly Haven map, our name, size in px, JPEG quality)
TEXTURES = {
    'asphalt_02': [('Diffuse', 'asphalt', 1024, 84), ('nor_gl', 'asphalt_n', 512, 86), ('Rough', 'asphalt_r', 512, 80)],
    'concrete_pavement': [('Diffuse', 'pavers', 1024, 84), ('nor_gl', 'pavers_n', 512, 86)],
    'concrete_floor_02': [('Diffuse', 'concrete', 512, 84), ('nor_gl', 'concrete_n', 512, 86)],
    'red_brick_03': [('Diffuse', 'brick', 1024, 84), ('nor_gl', 'brick_n', 512, 86)],
    'beige_wall_001': [('Diffuse', 'plaster', 512, 86), ('nor_gl', 'plaster_n', 512, 86)],
    'concrete_tile_facade': [('Diffuse', 'stone', 1024, 84), ('nor_gl', 'stone_n', 512, 86)],
}
HDRI = ('wide_street_01', 'sky_hdr', '1k')


def get(url, path):
    req = urllib.request.Request(url, headers={'User-Agent': 'car-crash-simulation asset fetch'})
    with urllib.request.urlopen(req, timeout=60) as r, open(path, 'wb') as f:
        f.write(r.read())


def files(asset):
    req = urllib.request.Request(API + asset, headers={'User-Agent': 'car-crash-simulation asset fetch'})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.loads(r.read())


def main():
    tmp = tempfile.mkdtemp(prefix='race-assets-')
    out = {}
    credits = []
    for asset, maps in TEXTURES.items():
        info = files(asset)
        for pmap, name, size, quality in maps:
            src = info[pmap]['1k']['jpg']['url']
            raw = os.path.join(tmp, name + '-raw.jpg')
            get(src, raw)
            img = bpy.data.images.load(raw)
            if pmap != 'Diffuse':
                img.colorspace_settings.name = 'Non-Color'   # keep the data values as they are
            if img.size[0] != size:
                img.scale(size, size)
            img.file_format = 'JPEG'
            dst = os.path.join(tmp, name + '.jpg')
            img.save(filepath=dst, quality=quality)
            bpy.data.images.remove(img)
            with open(dst, 'rb') as f:
                out[name] = base64.b64encode(f.read()).decode('ascii')
            print(f'{name}: {asset} {pmap} {size}px {os.path.getsize(dst) // 1024} KB')
        credits.append(asset)
    asset, name, res = HDRI
    info = files(asset)
    dst = os.path.join(tmp, name + '.hdr')
    get(info['hdri'][res]['hdr']['url'], dst)
    with open(dst, 'rb') as f:
        out[name] = base64.b64encode(f.read()).decode('ascii')
    print(f'{name}: {asset} {res} {os.path.getsize(dst) // 1024} KB')
    credits.append(asset)

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('/* Generated by tools/fetch-race-assets.py. Do not edit; re-run the tool.\n')
        f.write(' * Photo textures and sky from Poly Haven (polyhaven.com), CC0: ' + ', '.join(credits) + ' */\n')
        f.write('window.RACE_ASSETS = ' + json.dumps(out) + ';\n')
    print('wrote', OUT, os.path.getsize(OUT) // 1024, 'KB')


try:
    main()
except Exception as e:
    print('FAILED:', e)
    sys.exit(1)
